version: "3"
services:
  mysql:
    image: mysql:5.7
    network_mode: bridge
    container_name: mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=antenas

    restart: on-failure

  springbootapp:
    build: .
    network_mode: bridge
    container_name: antenas-backend
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=jdbc:mysql://mysql:3306/antenas?useTimezone=true&serverTimezone=UTC&useSSL=false
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql
